# Generated by Django 5.2.12 on 2026-03-18 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category_image",
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[("coupon", "Coupon Code"), ("automatic", "Automatic")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Expired", "Expired"),
                            ("Scheduled", "Scheduled"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave blank for unlimited", null=True
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("one_per_customer", models.BooleanField(default=False)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("none", "No Condition"),
                            ("min_order", "Minimum Order Amount"),
                            ("min_quantity", "Minimum Quantity"),
                            ("product", "Specific Product in Cart"),
                            ("category", "Specific Category in Cart"),
                            ("sub_category", "Specific Sub Category in Cart"),
                            ("first_order", "First Order Only"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Used when condition is min_order",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used when condition is min_quantity",
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("percentage_off", "Percentage Off"),
                            ("flat_off", "Flat Amount Off"),
                            ("free_shipping", "Free Shipping"),
                            ("free_product", "Free Product Added to Cart"),
                            ("bundle_price", "Fixed Bundle Price"),
                            ("bogo", "Buy X Get Y Free"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage or flat amount",
                        max_digits=10,
                    ),
                ),
                (
                    "max_discount_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max discount allowed (for percentage off)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "buy_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Buy X — for BOGO", null=True
                    ),
                ),
                (
                    "get_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Get Y free — for BOGO", null=True
                    ),
                ),
                (
                    "bundle_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stackable",
                    models.BooleanField(
                        default=False, help_text="Can this stack with other discounts?"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher number = applied first"
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle_products",
                    models.ManyToManyField(
                        blank=True, related_name="bundle_offers", to="dash.product"
                    ),
                ),
                (
                    "condition_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condition_offers",
                        to="dash.category",
                    ),
                ),
                (
                    "condition_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condition_offers",
                        to="dash.product",
                    ),
                ),
                (
                    "condition_sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condition_offers",
                        to="dash.subcategory",
                    ),
                ),
                (
                    "free_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_in_offers",
                        to="dash.product",
                    ),
                ),
                (
                    "free_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_in_offers",
                        to="dash.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
