# Generated by Django 5.2.12 on 2026-03-18 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0003_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="breadth",
            field=models.DecimalField(
                decimal_places=2, default=1.0, help_text="Breadth in cm", max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=1.0, help_text="Height in cm", max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="length",
            field=models.DecimalField(
                decimal_places=2, default=1.0, help_text="Length in cm", max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0.5, help_text="Weight in kg", max_digits=5
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_abandoned", models.BooleanField(default=False)),
                ("recovery_email_1", models.BooleanField(default=False)),
                ("recovery_email_2", models.BooleanField(default=False)),
                ("recovery_email_3", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="dash.customers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="dash.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dash.product"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.variant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("full_name", models.CharField(max_length=255)),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("razorpay", "Razorpay"), ("cod", "Cash on Delivery")],
                        default="razorpay",
                        max_length=20,
                    ),
                ),
                ("razorpay_order_id", models.CharField(blank=True, max_length=255)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=255)),
                ("razorpay_signature", models.CharField(blank=True, max_length=500)),
                ("payment_status", models.CharField(default="pending", max_length=50)),
                ("shiprocket_order_id", models.CharField(blank=True, max_length=255)),
                (
                    "shiprocket_shipment_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("awb_code", models.CharField(blank=True, max_length=255)),
                ("courier_name", models.CharField(blank=True, max_length=255)),
                ("shipping_status", models.CharField(blank=True, max_length=255)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("payment_failed", "Payment Failed"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("return_requested", "Return Requested"),
                            ("returned", "Returned"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="dash.customers",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="dash.offer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("variant_name", models.CharField(blank=True, max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gst", models.DecimalField(decimal_places=2, max_digits=5)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="dash.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash.variant",
                    ),
                ),
            ],
        ),
    ]
