# Generated by Django 5.2.12 on 2026-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0004_variant_breadth_variant_height_variant_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_breadth",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Widest item breadth in cm",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_height",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Combined height of all items in cm",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_length",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Longest item length in cm",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total order weight in kg",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="breadth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="length",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
