# Generated by Django 5.2.12 on 2026-09-23 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_order_total_breadth_order_total_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='Enabled', max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('show_in_nav', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('description', models.TextField(blank=True, null=True)),
                ('tldr_title', models.CharField(blank=True, max_length=1500, null=True)),
                ('tldr', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=1500)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=1500)),
                ('content', models.TextField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=1500, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='Enabled', max_length=100, null=True)),
                ('title_colour', models.CharField(blank=True, max_length=100)),
                ('banner_background_colour', models.CharField(blank=True, max_length=100)),
                ('remaining_text_colour', models.CharField(blank=True, max_length=100)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='articles/banners/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dash.articlecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='dash.article')),
            ],
            options={
                'verbose_name': 'Article FAQ',
                'verbose_name_plural': 'Article FAQs',
            },
        ),
        migrations.CreateModel(
            name='ArticleHowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=300)),
                ('step_text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='howto_steps', to='dash.article')),
            ],
            options={
                'verbose_name': 'Article How-To Step',
                'verbose_name_plural': 'Article How-To Steps',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='authors/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dash.author'),
        ),
    ]
